### ISSUE TITLE
Why not just use `Enum.to_list/1` for `REnum.to_a/1`?

### ISSUE THREAD

**Issue by mnishiguchi** [tashirosota/ex-r_enum#10]
Is there a particular reason why key-value pairs need to be lists?

**Comment by tashirosota** [comment]
@mnishiguchi 
I wanted it to behave like Ruby as much as possible! But I'm a little worried about this.
I think it's more natural to call to_list too.What do you think?
https://docs.ruby-lang.org/ja/latest/method/Hash/i/to_a.html

**Comment by mnishiguchi** [comment]
Ruby does not have tuples. Elixir has tuples and linked lists.
I believe tuples are more efficient than lists in Elixir. 
Key-value pairs are always two elements long so I wonder if there is any benefit of using list as a data structure there 🤔 

In the end, it is about a design decision so if list makes sense in this context, I guess list is fine 😄

**Comment by tashirosota** [comment]
@mnishiguchi 
I thought about it overnight, but the behavior on to_list seems more natural in Elixir, so I'll try to adjust it accordingly!
Such an opinion is very helpful. Thank you!

**Comment by mnishiguchi** [comment]
NP! Actually I have a few more things to say 😁 

Is it intentional to output differently between maps and lists?

```elixir
iex> REnum.to_a(a: 1, b: 2, c: 2, d: 4)
[{:a, 1}, {:b, 2}, {:c, 2}, {:d, 4}]  #<-- list of tuples

iex> REnum.to_a(%{a: 1, b: 2, c: 2, d: 4})
[[:a, 1], [:b, 2], [:c, 2], [:d, 4]] #<-- list of lists
```

Ruby `to_a` implies "to array" and we do not have arrays in Elixir. Maybe we could skip implementing some Ruby methods that do not make sense in Elixir world?

With that all said, it is a design decision. It is all your call 😄 

**UPDATES**

- My apologies, I realized that you already delegate it to `Enum.to_list/1` in an PR and it solves it!
