### ISSUE TITLE
hexdocsの目次から各関数へジャンプできない

### ISSUE THREAD

**Issue by yellowsman** [tashirosota/ex-r_enum#35]
REnumのhexdocの目次に書かれているリンク先と、実際の各項目ごとのリンクが異なっているようです。
hexdocs: https://hexdocs.pm/r_enum/readme.html

・目次のリンク: https://hexdocs.pm/r_enum/readme.html#compact1
・各項目のリンク: https://hexdocs.pm/r_enum/readme.html#compact-1

**Comment by tashirosota** [comment]
ありがとうございます！
generatorを使ってたのですが、そちらがバグってたみたいですね。
確認いたします！

**Comment by yellowsman** [comment]
対応ありがとうございました！
